import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';

export default function ExperiencesPage() {
  return <SiteLayout>
    <section className="page-hero editorial-page-hero"><div className="container narrow"><p className="eyebrow">A PLACE TO BEGIN</p><h1>Start with one evening.</h1><p className="page-lead">ROAMSIX events bring carefully selected experts into rooms small enough to ask questions, hear different perspectives, and experience an idea beyond the stage.</p></div></section>
    <section className="section light-section"><div className="container">
      <article className="experience-feature-card"><figure className="experience-event-image"><img src="/images/homepage/roamsix-outdoor-panel-bw-v1.jpg" alt="An intimate outdoor panel conversation with an audience." /></figure><p className="eyebrow">OCTOBER 24, 2026 · SAN DIEGO COUNTY · 25 SEATS</p><h2>The gut-brain connection: food, stress, and everyday performance</h2><p><Link to="/experiences#dr-sal">Dr. Sulaiman Bharwani</Link>, pediatric gastroenterologist and founder of GutRewired, on how food, stress, and sleep interact, and which gut-health advice holds up.</p><p>$50 holds your seat. The exact location is released October 7. Full refund if the location does not work for you. Your ticket applies toward founding membership if you join within 48 hours of the event.</p><Link className="button button-accent" to="/events/dr-sal-gut-brain-2026?source=experiences">Hold my seat · $50</Link></article>
    </div></section>
    <section className="section ink-section" id="dr-sal"><div className="container expert-profile">
      <figure className="expert-profile-photo"><img src="/images/experts/dr-sulaiman-bharwani-gutrewired-v2.jpg" alt="Dr. Sulaiman Bharwani." /></figure>
      <div><p className="eyebrow">Featured expert</p><h2>Dr. Sulaiman “Sal” Bharwani</h2><p className="profile-role">Founder and CEO, Lifax Longevity and GutRewired</p><p className="lead">Dr. Sulaiman “Sal” Bharwani is founder and CEO of Lifax Longevity and GutRewired. A board-certified gastroenterologist and board-certified nutritionist, he brings more than 30 years of experience across clinical care, research, and medical education, with a focus on the gut-brain connection, microbiome, nutrition, and longevity.</p><p className="lead">An alumnus of Brown University School of Medicine and the University of Chicago, Dr. Bharwani completed hepatology and liver-transplant training at Harvard, Tufts, and Baylor, and nutrition training at The Hospital for Sick Children/University of Toronto. He has published nearly 100 peer-reviewed papers and abstracts, cited close to 3,000 times, and has led pediatric GI programs in the United States, Canada, and the UAE while helping establish programs internationally.</p><p className="lead">His honors include the Southern Society Research Award, Castle Connolly Top Doctor recognition for the past two consecutive years, and a United Kingdom Liver Foundation award. Through GutRewired, he translates complex science into practical health education. At ROAMSIX on October 24, he will help guests examine how food, stress, sleep, the microbiome, and the gut-brain connection interact in everyday life.</p><nav className="expert-profile-links" aria-label="Dr. Sulaiman Bharwani links"><a href="https://www.gutrewired.com" target="_blank" rel="noreferrer">GutRewired</a><a href="https://www.instagram.com/gutrewired/" target="_blank" rel="noreferrer">Instagram · @Gutrewired</a><a href="https://www.youtube.com/@gutrewired" target="_blank" rel="noreferrer">YouTube · @gutrewired</a></nav></div>
    </div></section>
    <section className="section fog-section"><div className="container organization-options"><article><p className="eyebrow">Explore what is ahead</p><h2>Four themes. A more complete view of your health.</h2><p>See how gut health, recovery, focus, and longevity influence one another.</p><Link className="button" to="/events">Explore the themes</Link></article><article><p className="eyebrow">Go beyond one event</p><h2>Keep going beyond one event.</h2><p>Membership includes all 36 Core gatherings in 2027, so one evening can become part of a full year of conversations, movement, and hands-on experiences.</p><Link className="button button-accent" to="/membership">Compare membership options</Link></article></div></section>
  </SiteLayout>;
}
