import { useState } from 'react';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import TopicInterestForm from '../components/TopicInterestForm';
import { FIELDWORK_PROGRAM } from '../data/fieldworkProgram';

export default function FieldworkPage() {
  const [interest, setInterest] = useState({ id: '2027-program', label: '2027 themes and calendar updates' });
  const chooseInterest = (id, label) => { setInterest({ id, label }); window.requestAnimationFrame(() => document.querySelector('#interest')?.scrollIntoView({ block: 'start' })); };
  return <SiteLayout>
    <section className="page-hero editorial-page-hero"><div className="container narrow"><p className="eyebrow">2027 themes &amp; calendar</p><h1>Your health does not happen in separate categories.</h1><p className="page-lead">Gut health, recovery, focus, and longevity influence one another. Follow all four themes across the year and join the experiences that are relevant to you.</p><button className="button" type="button" onClick={() => chooseInterest('2027-program', '2027 themes and calendar updates')}>Send me 2027 updates</button></div></section>
    <section className="section light-section" id="quarters"><div className="container"><h2>Four subjects, one system</h2><p className="section-intro">These are not four topics you choose between. Gut health, recovery, focus, and longevity are four views of the same body. Following one and ignoring the rest is how people end up with four sets of advice that contradict each other.</p><div className="quarter-overview-grid">{FIELDWORK_PROGRAM.map((quarter) => <article key={quarter.slug}><p className="eyebrow">{quarter.quarter}</p><h3>{quarter.subject}</h3><p className="theme-tagline">{quarter.title}</p><p>{quarter.recognition}</p><p>{quarter.outcome}</p><p className="theme-fields">{quarter.fields}</p><div className="quarter-card-actions"><Link className="button button-secondary" to={`/events/${quarter.slug}`}>Explore this theme</Link><button className="button" type="button" onClick={() => chooseInterest(`${quarter.slug}-theme`, quarter.subject)}>Tell me when it opens</button></div></article>)}</div></div></section>
    <section className="journey-feature"><img src="/images/homepage/roamsix-journey-mediterranean-v2.jpg" alt="A small group exploring a Mediterranean coastal landscape with a local guide." /><div className="journey-feature-shade" aria-hidden="true" /><div className="container journey-feature-copy"><p className="eyebrow">The year-end Journey · Multi-day immersion</p><h2>The year ends somewhere else.</h2><p>A multi-day immersion built from everything the year covered, somewhere with nothing to do with your routine. Purchased separately. Dates, destination, and pricing shared before reservations open.</p><button className="button button-accent" type="button" onClick={() => chooseInterest('year-end-journey', 'The 2027 year-end Journey')}>Send me Journey updates</button></div></section>
    <section className="section fog-section" id="interest"><div className="container form-layout"><div><p className="eyebrow">Relevant updates</p><h2>Tell us what you want to explore next.</h2><p>Choose a theme or the Journey, and we will send the dates, locations, and booking details for that interest as they are confirmed.</p></div><TopicInterestForm interest={interest} /></div></section>
  </SiteLayout>;
}
