import { useState } from 'react';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import TopicInterestForm from '../components/TopicInterestForm';
import { FIELDWORK_PROGRAM } from '../data/fieldworkProgram';

export default function FieldworkPage() {
  const [interest, setInterest] = useState({ id: '2027-program', label: '2027 themes and calendar updates' });
  const chooseInterest = (id, label) => { setInterest({ id, label }); window.requestAnimationFrame(() => document.querySelector('#interest')?.scrollIntoView({ block: 'start' })); };
  return <SiteLayout>
    <section className="page-hero editorial-page-hero"><div className="container narrow"><p className="eyebrow">2027 themes &amp; calendar</p><h1>Your health does not happen in separate categories.</h1><p className="page-lead">Gut health, recovery, focus, and longevity influence one another. Follow all four themes across the year and join the experiences that are relevant to you.</p><button className="button" type="button" onClick={() => chooseInterest('2027-program', '2027 themes and calendar updates')}>Send me 2027 updates</button></div></section>
    <section className="section light-section" id="quarters"><div className="container"><p className="eyebrow">A more complete view of your health</p><h2>Enter at any point. You will not have missed the beginning.</h2><p className="section-intro">Each theme stands on its own while adding another perspective to the larger picture. Explore what feels relevant now, then return when another subject speaks to you.</p><div className="quarter-overview-grid">{FIELDWORK_PROGRAM.map((quarter) => <article key={quarter.slug}><p className="eyebrow">{quarter.quarter}</p><h3>{quarter.subject}</h3><p className="theme-tagline">{quarter.title}</p><p>{quarter.recognition}</p><p>{quarter.outcome}</p><p className="theme-fields">{quarter.fields}</p><div className="quarter-card-actions"><Link className="button button-secondary" to={`/events/${quarter.slug}`}>Explore this theme</Link><button className="button" type="button" onClick={() => chooseInterest(`${quarter.slug}-theme`, quarter.subject)}>Tell me when it opens</button></div></article>)}</div></div></section>
    <section className="section ink-section"><div className="container split-copy"><p className="eyebrow">The ongoing path</p><div><h2>See patterns that one event cannot reveal.</h2><p className="lead">Join at any point. Each experience adds another perspective on how the different parts of your health connect.</p><Link className="button button-secondary" to="/membership">Find my place in ROAMSIX</Link></div></div></section>
    <section className="fieldwork-cta capstone-cta"><div className="container"><div><p className="eyebrow">The year-end Journey · Multi-day immersion</p><h2>Step away from routine and see the whole picture differently.</h2><p>The optional Journey brings gut health, recovery, focus, and longevity into one spacious experience. It is purchased separately by every traveler and proceeds only after required deposits and minimum participation are secured.</p></div><button className="button" type="button" onClick={() => chooseInterest('year-end-journey', 'The 2027 year-end Journey')}>Send me Journey updates</button></div></section>
    <section className="section fog-section" id="interest"><div className="container form-layout"><div><p className="eyebrow">Calendar updates</p><h2>Be first to know what opens next.</h2><p>Choose what you want to follow and we will send the relevant dates, locations, and booking details.</p></div><TopicInterestForm interest={interest} /></div></section>
  </SiteLayout>;
}
