import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ExperienceFinder from '../components/ExperienceFinder';

export default function HomePage() {
  return <SiteLayout theme="dark">
    <section className="hero home-hero"><div className="hero-image" aria-hidden="true" /><div className="hero-shade" aria-hidden="true" /><div className="hero-content container">
      <p className="eyebrow">Southern California · 36 gatherings in 2027</p><h1>Health advice is everywhere. Knowing what deserves your attention is harder.</h1>
      <p className="hero-copy">ROAMSIX is a membership built around live gatherings. In 2027 we run 36 of them: fireside conversations with vetted specialists, and movement mornings outdoors. Four subjects, one quarter each.</p>
      <div className="button-row"><Link className="button button-accent" to="/membership">Explore membership</Link><Link className="text-link light" to="/experiences">Attend an upcoming event <span aria-hidden="true">→</span></Link></div>
    </div></section>
    <section className="fieldwork-cta membership-home-cta"><div className="container"><div><p className="eyebrow">Founding membership · Closes December 31</p><h2>The rate you join at is the rate you keep.</h2><p>ROAMSIX opens in 2027 with 36 gatherings across four subjects. Founding members join before that year begins and hold their rate for as long as their membership stays active.</p><p>The four subjects are set. The specialists, the venues, and the specific questions are not. Founding members help decide those. We would rather build the first year with the people who are in it.</p><p>Core is $850 for founding members. It becomes $900 in 2027.</p></div><div className="button-column"><Link className="button" to="/membership/checkout/core">Join Core · $850/year</Link><Link className="text-link light" to="/membership#request-membership">Talk it through first</Link></div></div></section>
    <section className="section light-section"><div className="container membership-value-intro"><h2>Why ROAMSIX</h2><div><p className="lead">Health information is not scarce. Usable health information is. Most people managing their own health are evaluating every claim alone, with no way to tell a real finding from a marketing cycle.</p><p><strong>We do the filtering.</strong> Every specialist is selected, briefed, and vetted before a member spends an evening with them. No one buys their way onto the program.</p><p><strong>We follow a subject long enough to matter.</strong> Each of the four 2027 subjects gets a full quarter: gut health, sleep and recovery, focus and resilience, strength and longevity. Not one talk and a newsletter.</p><p><strong>The room is small enough to ask.</strong> Most gatherings cap at 25 to 40 people. You put your question to the specialist directly instead of watching someone else's.</p></div></div></section>
    <section className="section light-section"><div className="container feature-grid"><figure className="feature-image sal-fireside-image"><img src="/images/homepage/roamsix-outdoor-panel-bw-v1.jpg" alt="An intimate outdoor panel conversation with an audience." /></figure><div className="feature-copy">
      <p className="eyebrow">October 24, 2026 · San Diego</p><h2>Gut-health advice is everywhere. Clear guidance is harder to find.</h2><p>Dr. Sulaiman Bharwani joins ROAMSIX for a conversation about the gut-brain connection, food, stress, and everyday performance. The venue will be announced and registration is not yet open.</p><Link className="button button-accent" to="/experiences">Tell me when registration opens</Link>
    </div></div></section>
    <section className="section fog-section"><div className="container"><p className="eyebrow">Your path into ROAMSIX</p><h2>Start with a question. Build toward a clearer understanding.</h2><div className="member-path-grid">
      <article><span>01</span><h3>Begin with what matters now.</h3><p>Choose a timely subject or event rather than trying to solve every part of your health at once.</p></article>
      <article><span>02</span><h3>Learn through a complete lens.</h3><p>Move from evidence and expert interpretation into practical education and firsthand experience.</p></article>
      <article><span>03</span><h3>Use the insight.</h3><p>Identify the next decision, resource, assessment, or experience that can move you forward.</p></article>
    </div><div className="button-row"><Link className="button button-accent" to="/membership">See how membership works</Link></div></div></section>
    <section className="section fog-section"><div className="container organization-callout"><p className="eyebrow">For organizations</p><h2>You optimize systems. Human performance deserves the same intention.</h2><p className="lead">Your people can be capable and committed while still needing better ways to understand energy, recovery, focus, resilience, and long-term performance. ROAMSIX builds the right expert-led experience around the outcome you care about.</p><Link className="button button-accent" to="/organizations">Explore what could help my team</Link></div></section>
    <section className="section fog-section home-finder-section" id="find-your-fit"><div className="container finder-layout"><div><p className="eyebrow">Find the right way in</p><h2>Tell us who you are and what matters now.</h2><p className="lead">We will point you toward the ROAMSIX subject, experience, or membership path most relevant to you.</p></div><ExperienceFinder compact /></div></section>
  </SiteLayout>;
}
