import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ExperienceFinder from '../components/ExperienceFinder';

export default function HomePage() {
  return <SiteLayout theme="dark">
    <section className="hero home-hero"><div className="hero-image" aria-hidden="true" /><div className="hero-shade" aria-hidden="true" /><div className="hero-content container">
      <p className="eyebrow">SOUTHERN CALIFORNIA · 2027</p><h1>Figure out what actually works for you.</h1>
      <p className="hero-copy"><strong>An experiential health discovery membership.</strong> Small-group gatherings where physicians, researchers and practitioners get in the same room with you, so you can ask questions, hear different perspectives and try ideas for yourself.</p>
      <p className="hero-copy"><strong>36 gatherings. Four subjects. Each one gets a full quarter.</strong></p>
      <div className="button-row"><Link className="button button-accent" to="/membership">Explore membership</Link><Link className="text-link light" to="/experiences">Attend an upcoming event <span aria-hidden="true">→</span></Link></div>
    </div></section>
    <section className="fieldwork-cta membership-home-cta"><div className="container"><div><p className="eyebrow">Founding membership · Closes December 31</p><h2>The rate you join at is the rate you keep.</h2><p>ROAMSIX opens in 2027 with 36 gatherings across four subjects. Founding members join before that year begins and hold their rate for as long as their membership stays active.</p><p>The four subjects are set. The experts, the venues, and the specific questions are not. Founding members help decide those. We would rather build the first year with the people who are in it.</p><p>Core is $850 for founding members. It becomes $1,100 in 2027.</p></div><div className="button-column"><Link className="button" to="/membership/checkout/core">Join Core · $850/year</Link><Link className="text-link light" to="/membership#request-membership">Talk it through first</Link></div></div></section>
    <section className="section light-section"><div className="container membership-value-intro"><h2>What we are not</h2><div><p><strong>Not a clinic.</strong> We do not diagnose, treat, or prescribe. We help you understand the question well enough to ask it properly.</p><p><strong>Not a wellness brand.</strong> Nothing we bring you has a supplement attached to it.</p><p><strong>Not a conference.</strong> Rooms cap at 25 to 40 people. You are expected to talk.</p><p><strong>Not a protocol.</strong> You leave with your own conclusions, not our checklist.</p></div></div></section>
    <section className="section light-section"><div className="container feature-grid"><figure className="feature-image sal-fireside-image"><img src="/images/homepage/roamsix-outdoor-panel-bw-v1.jpg" alt="An intimate outdoor panel conversation with an audience." /></figure><div className="feature-copy">
      <p className="eyebrow">OCTOBER 24, 2026 · SAN DIEGO COUNTY · 25 SEATS</p><h2>The gut-brain connection: food, stress, and everyday performance</h2><p><Link to="/experiences#dr-sal">Dr. Sulaiman Bharwani</Link>, pediatric gastroenterologist and founder of GutRewired, on how food, stress, and sleep interact, and which gut-health advice holds up.</p><p>$50 holds your seat. The exact location is released October 7. Full refund if the location does not work for you. Your ticket applies toward founding membership if you join within 48 hours of the event.</p><Link className="button button-accent" to="/events/dr-sal-gut-brain-2026?source=homepage">Hold my seat · $50</Link>
    </div></div></section>
    <section className="section fog-section"><div className="container"><p className="eyebrow">Your path into ROAMSIX</p><h2>Start with a question. Build toward a clearer understanding.</h2><div className="member-path-grid">
      <article><span>01</span><h3>Begin with what matters now.</h3><p>Choose a timely subject or event rather than trying to solve every part of your health at once.</p></article>
      <article><span>02</span><h3>Learn through a complete lens</h3><p>Move from evidence and expert interpretation into practical knowledge and firsthand experience.</p></article>
      <article><span>03</span><h3>Leave with your next move</h3><p>The specific question to ask, the thing worth trying, or the person worth seeing. Not a checklist.</p></article>
    </div><div className="button-row"><Link className="button button-accent" to="/membership">See how membership works</Link></div></div></section>
    <section className="section fog-section"><div className="container organization-callout"><p className="eyebrow">For organizations</p><h2>You optimize systems. Human performance deserves the same intention.</h2><p className="lead">Your people can be capable and committed while still needing better ways to understand energy, recovery, focus, resilience, and long-term performance. ROAMSIX builds the right expert-led experience around the outcome you care about.</p><Link className="button button-accent" to="/organizations">Explore what could help my team</Link></div></section>
    <section className="section fog-section home-finder-section" id="find-your-fit"><div className="container finder-layout"><div><p className="eyebrow">Find the right way in</p><h2>Tell us who you are and what matters now.</h2><p className="lead">We will point you toward the ROAMSIX subject, experience, or membership path most relevant to you.</p></div><ExperienceFinder compact /></div></section>
  </SiteLayout>;
}
