import SiteLayout from '../components/SiteLayout';
import { Link } from 'react-router-dom';

export default function HowItWorksPage() {
  return <SiteLayout>
    <section className="page-hero"><div className="container narrow"><p className="eyebrow">How ROAMSIX works</p><h1>We turn health knowledge into something people can live.</h1><p className="page-lead">Each experience connects credible expertise with the setting, activities, and practice that make it useful.</p><Link className="button button-accent" to="/#find-your-fit">Find the right experience</Link></div></section>
    <section className="section light-section"><div className="container process-intro"><p className="eyebrow">The method</p><h2>Three parts. One clear outcome.</h2></div><div className="container journey-list"><article><span className="journey-number">01</span><div><h3>Define the change.</h3><p>Start with what someone should understand, practice, or do differently.</p></div></article><article><span className="journey-number">02</span><div><h3>Build the conditions.</h3><p>Bring together the right experts, setting, food, movement, activities, and conversation.</p></div></article><article><span className="journey-number">03</span><div><h3>Carry it forward.</h3><p>Leave with practices, decisions, and relationships that continue after the experience.</p></div></article></div></section>
    <section className="section ink-section format-section"><div className="container split-copy"><p className="eyebrow">Formats</p><div><h2>Give the idea enough time to become useful.</h2><p className="lead">An evening introduces one clear idea. A full day adds guided practice. A weekend creates time for deeper learning and recovery. Membership helps you continue throughout the year.</p></div></div><div className="container inline-pillars"><span>One evening</span><span>One day</span><span>One weekend</span><span>Several days</span><span>Ongoing</span></div></section>
    <section className="section fog-section"><div className="container organization-callout"><p className="eyebrow">Find your path</p><h2>Start with what you want to explore.</h2><Link className="button button-accent" to="/#find-your-fit">Use the experience finder</Link></div></section>
  </SiteLayout>;
}
