import SiteLayout from '../components/SiteLayout';
import { Link } from 'react-router-dom';

export default function HowItWorksPage() {
  return <SiteLayout>
    <section className="page-hero editorial-page-hero"><div className="container narrow"><p className="eyebrow">How ROAMSIX works</p><h1>A good experience changes what you notice afterward.</h1><p className="page-lead">ROAMSIX gives you space to understand an important idea, consider it in the context of your life, and leave with greater clarity.</p><Link className="button button-accent" to="/#find-your-fit">Find my starting point</Link></div></section>
    <section className="section light-section"><div className="container process-intro"><p className="eyebrow">The ROAMSIX framework</p><h2>Start with your life, not a generic formula.</h2><p className="lead">Understand what matters, see how the pieces connect, and experience useful ideas in practice.</p><p className="selection-standard"><strong>How we select experts:</strong> We look for rigor in their work, relevance in their perspective, and an ability to communicate complexity without oversimplifying it.</p></div><div className="container framework-list">
      <article><span>01 · Research &amp; Science</span><h3>Discover what matters.</h3><p>Begin with a subject that feels relevant to how you want to live, feel, or perform.</p></article>
      <article><span>02 · Clinical Perspective</span><h3>Interpret the evidence.</h3><p>Hear nuanced perspectives that help separate useful evidence from noise and oversimplification.</p></article>
      <article><span>03 · Specialist Expertise</span><h3>Connect the pieces.</h3><p>See how different parts of health influence one another instead of treating each one in isolation.</p></article>
      <article><span>04 · Practical Education</span><h3>Apply it to your life.</h3><p>Consider what feels relevant to your priorities without being handed a one-size-fits-all prescription.</p></article>
      <article><span>05 · Hands-On Experience</span><h3>Experience it firsthand.</h3><p>Use movement, food, place, and participation to understand an idea beyond the abstract.</p></article>
      <article><span>06 · Objective Insight &amp; Relevant Access</span><h3>Know where you stand.</h3><p>Where relevant partnerships are available, ROAMSIX may introduce trusted practitioners, laboratories, assessments, tools, and services that can help you establish a clearer starting point. Any testing, diagnosis, clinical interpretation, or medical guidance is provided by the qualified third party responsible for that service.</p></article>
    </div></section>
    <section className="section ink-section format-section"><div className="container split-copy"><p className="eyebrow">Ways to experience ROAMSIX</p><div><h2>Choose the depth that fits the question.</h2><p className="lead">A focused conversation can bring clarity. An immersive day can turn an idea into something felt and practical. Membership and the year-end Journey let you explore more deeply across time, place, and perspective.</p><Link className="button button-secondary" to="/#find-your-fit">Find the right way in</Link></div></div><div className="container inline-pillars"><span>Focused conversations</span><span>Immersive days</span><span>Movement and nature</span><span>Year-end Journey</span><span>Ongoing membership</span></div></section>
    <section className="section fog-section"><div className="container organization-callout"><p className="eyebrow">Your next step</p><h2>Tell us who you are, what matters now, and what you want to understand.</h2><Link className="button button-accent" to="/#find-your-fit">Find the right way in</Link></div></section>
  </SiteLayout>;
}
